⚡️ Ignore case sensitive for `flutter_style_todos`
dart-lang/linter pull request #3618
Opened 2022-08-26 05:09 UTC by AlexV525

Fixes #3616

2022-08-29 18:47 UTC, pq commented
As per @goderbauer's comment in https://github.com/dart-lang/linter/issues/3616#issuecomment-1230548924, I'm thinking we want to treat this lint as WAI and close this out.

Feel free to chime in on the issue and if you can change the Flutter team's mind, we can re-open.

Thanks so much for the contribution!

2022-08-30 14:10 UTC, AlexV525 commented
@pq Can we re-open this since we have some more detailed statements discussed in the issue?

2022-08-30 16:31 UTC, pq commented
While we're here, we might consider re-writing this check to not use regular expressions.  It's pretty slow as is and adding case insensitivity to the regexp slows it down even more...

Before this change:

![image](https://user-images.githubusercontent.com/67586/187490690-95d05fea-3cb6-4f55-8372-accb093c6950.png)

After:

![image](https://user-images.githubusercontent.com/67586/187490711-f6a37222-18ec-4fb0-bceb-64b1a5e11420.png)

(Note that absolute timings aren't reliable but I find the relative ranking useful.)

2022-08-30 16:38 UTC, pq commented
You'll want to update tests too.

```

00:55 +226: rule dart flutter_style_todos

// Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
// test w/ `dart test -N flutter_style_todos`
// TODO something //LINT
// Todo something //LINT
// todo something //LINT
CompilationUnitImpl [] // Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file


/home/runner/work/linter/linter/test_data/rules/flutter_style_todos.dart 7:1 [lint] Use Flutter TODO format: // TODO(username): message, https://URL-to-issue.
// TODO something //LINT
^^^^^^^^^^^^^^^^^^^^^^^^
/home/runner/work/linter/linter/test_data/rules/flutter_style_todos.dart 8:1 [lint] Use Flutter TODO format: // TODO(username): message, https://URL-to-issue.
// Todo something //LINT
^^^^^^^^^^^^^^^^^^^^^^^^
/home/runner/work/linter/linter/test_data/rules/flutter_style_todos.dart 9:1 [lint] Use Flutter TODO format: // TODO(username): message, https://URL-to-issue.
// todo something //LINT
^^^^^^^^^^^^^^^^^^^^^^^^

null files analyzed, 3 issues found, in null ms.

00:55 +226 -1: rule dart flutter_style_todos [E]

  Expected: matches [] unordered
    Actual: [
              Annotation:[LINT]: "Use Flutter TODO format: // TODO(username): message, https://URL-to-issue." (line: 7) - [1:24],
              Annotation:[LINT]: "Use Flutter TODO format: // TODO(username): message, https://URL-to-issue." (line: 8) - [1:24],
              Annotation:[LINT]: "Use Flutter TODO format: // TODO(username): message, https://URL-to-issue." (line: 9) - [1:24]
            ]
     Which: has too many elements (3 > 0)
```

https://github.com/dart-lang/linter/runs/8096820336?check_suite_focus=true

2022-08-30 16:39 UTC, AlexV525 commented
> You'll want to update tests too.

I was checking this. The rule test doesn't seem to support `// LINT` after TODOs, as they'll be recognized as a part of the TODO. Any thoughts? @pq

2022-08-30 16:43 UTC, pq commented on test/rules/flutter_style_todos_test.dart
> +// Copyright (c) 2022, the Dart project authors. Please see the AUTHORS file
You'll want to add this to `all.dart`.

2022-08-30 16:43 UTC, pq commented on test_data/rules/flutter_style_todos.dart
> +// Copyright (c) 2020, the Dart project authors. Please see the AUTHORS file
I'd remove this test data file and just test in the reflective test style.

2022-09-01 14:33 UTC, bwilkerson approved these changes

2022-09-01 16:27 UTC, pq commented
Hey @AlexV525!  This is great, thanks.  I'm going to hold on landing this until after 1.28.0.  That release is blocking an analyzer roll and I don't want to jeopardize that with any other changes that could cause issues with our internal roll.

That said, we can get working on another release soonish after.

Cheers!

2022-09-01 21:45 UTC, pq commented on test/rules/flutter_style_todos_test.dart
> +      [
I can't actually tell from looking at this list where the expected failures are.  Could you consider (at least) breaking these up into one test for OK patterns and another for bad ones?

2022-09-01 21:46 UTC, pq commented
Not necessarily for this PR but I still think it'd be great to look at improving the performance of this lint. 🤔

2022-09-01 21:47 UTC, pq requested changes
Assuming I understand where the failures are supposed to be (see comment) LGTM! :D

2022-09-02 03:12 UTC, AlexV525 commented
> Not necessarily for this PR but I still think it'd be great to look at improving the performance of this lint. 🤔

We can maybe keep it tracked in separate issues. I will file a new one after it's landed.

2022-09-14 22:11 UTC, pq approved these changes

2022-09-14 22:11 UTC, merged